baseurl = "https://radiant-trifle-780080.netlify.app/"
languageCode = "da"
languageLang = "da"
title = "Palæstinas Plads"  

[params]
  description = "Tesla's Awesome Hugo Site"
  instaUrl = "https://instagram.com"
  twitterUrl = "https://twitter.com"
  facebookUrl = "https://facebook.com"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy"]
